### PR TITLE
DistributedItentity: rename to DecentralizedIdentifier

### LINKED ISSUE #435: Naming - DID - Rename Distributed Identity to Decentralized Identifier
Rename the package `extensions/iam/distributed-identity/..` to `extensions/iam/decentralized-identifier/..`

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### PR DESCRIPTION
**Pull request by bcronin90**
Closes #435 

This PR renames the "distributed-identity" extension to "decentralized-identifier".

Brendan Cronin brendan.cronin@daimler.com, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

### CODE REVIEW

**Review by paullatzelsperger — APPROVED** [review]
LGTM.﻿

**Review by ndr-brt — APPROVED** [review]

**Comment by jimmarino** [comment]
Sorry I didn't yet have time to review this until now. I like most parts of the PR but don't think we should call these extensions "Decentralized Identifier" since they don't just deal with DIDs, they implement a Decentralized Identity subsystem. So, I like the idea of changing from Distributed to Decentralized since that nicely covers our shift to focus on identity solutions that leverage things like DNS (e.g. Web DIDs) s opposed to just blockchain ("decentralized")

This was already an issue with the existing naming scheme, so I don't think it is a problem per se with this PR.

Related, DecentralizedIdentifierService should be DecentralizedIdentityService.

@bcronin90 is this something you have time to discuss and work on an approach that can address that?

**Comment by bcronin90** [comment]
@jimmarino Sure. We can reopen the issue. Would you like to have a quick call for this?

**Comment by bcronin90** [comment]
@jimmarino We checked this internally. We're okay with changing the name again. I'll reopen the issue and work on it.

**Pull request merged**
