### PR TITLE
contract-validation: add validation of agreement start/end time (closes #295)

### LINKED ISSUE #295: `ContractValidationService` Add functionality
This issue is about adding the following functionality to the `ContractValidationService`:

- The contract validation service should be able to tell when a contract is expired
- The contract validation service should also check whether the corresponding asset is part of the contract
- The contract validation service should return a result object with found errors, so that the caller is able to log them with some context information.

Additionally the `ContractValidationService` checks currently in two places whether a `contract` id is valid. Therefore it would be nice if
- The `contract id` would be a value objects, that cannot be formatted incorrectly. So that we don't need this checks in several places. 

Update:
> The contract validation service should also check whether the corresponding asset is part of the contract

This requirement will become invalid as future `ContractAgreement` will only contain one `Asset` -> Ignore it.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### PR DESCRIPTION
**Pull request by DominikPinsel**
Signed-off-by: Dominik Pinsel <dominik.pinsel@daimler.com>
Signed-off-by: Denis Neuling <denis.neuling@daimler.com>
Co-authored-by: Denis Neuing <denis.neuling@daimler.com>

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### CODE REVIEW

**Comment by DominikPinsel** [comment]
@jimmarino introduces all the changes we talked about. Please take another look :)

**Comment by jimmarino** [comment]
@DominikPinsel this PR is doing too many things. As discussed previously, the validation should only return a boolean and not give any indication to the client why the validation failed. Otherwise, this may create a security vulnerability. Details of why the validation failed can be passed to the monitor and correlated by an operations team. Please see how `IdentityService` works for an analogous example.

Also, the PR is changing code formatting in unrelated classes (which already passed Checkstyle) and reactors method signatures that don't need to be modified. That makes it difficult to understand what the intent of the PR is.

I think this PR should be a very small addition to check timestamps.

**Comment by DominikPinsel** [comment]
> @DominikPinsel this PR is doing too many things. As discussed previously, the validation should only return a boolean and not give any indication to the client why the validation failed. Otherwise, this may create a security vulnerability. Details of why the validation failed can be passed to the monitor and correlated by an operations team. Please see how `IdentityService` works for an analogous example.
> 
> Also, the PR is changing code formatting in unrelated classes (which already passed Checkstyle) and reactors method signatures that don't need to be modified. That makes it difficult to understand what the intent of the PR is.
> 
> I think this PR should be a very small addition to check timestamps.

finished

**Review by jimmarino — APPROVED** [review]
@DominikPinsel thanks!

**Pull request merged**
