### PR TITLE
core: upgrade to Jetty 11.0.8

### LINKED ISSUE #896: Upgrade to Jetty 11.0.8

### PR DESCRIPTION
**Pull request by jbonofre**
## What this PR changes/adds

Upgrade to jetty 11.0.8

## Why it does that

Jetty 11.0.8 includes couple of CVE and several bug fixes.

## Issue

This closes #896

### CODE REVIEW

**Comment by jimmarino** [comment]
@jbonofre can you sign the CLA?

**Comment by jbonofre** [comment]
Hey @jimmarino. Actually I already signed CLA/ECA while ago, just updated it this morning. Let me double check and trigger a new check CI to verify it's OK now. Thanks !

**Comment by jimmarino** [comment]
OK, almost there. Can you please add an entry in the Milestone 3 section of the changelog?

**Comment by jimmarino** [comment]
OK, almost there. Can you please add an entry in the Milestone 3 section of the changelog?

**Comment by jbonofre** [comment]
@jimmarino sure, let me do that. Thanks !

**Comment by jbonofre** [comment]
And also, I gonna check about ECA/ICLA again.

**Review by ndr-brt — APPROVED** [review]

**Comment by bscholtes1A** [comment]
Hi @jbonofre ,
is there any update on this PR? How can we move forward?

**Comment by jbonofre** [comment]
Hey. Sorry for the delay. I will rebase and update the PR. My CLA should be sorted out now. I will rework on it today/tomorrow. I also have other changes in progress (for new PRs).

**Comment by jbonofre** [comment]
Hey. Sorry for the delay. I will rebase and update the PR. My CLA should be sorted out now. I will rework on it today/tomorrow. I also have other changes in progress (for new PRs).

**Comment by jbonofre** [comment]
Rebased.
I'm checking with my ECA is not linked here.

**Comment by jbonofre** [comment]
OK, I think I got it: my commit email address is not the same as in my ECA. Trying to rebase/squash with the correct email address.

**Comment by jbonofre** [comment]
ECA OK now :)

**Comment by jbonofre** [comment]
@bscholtes1A @jimmarino can you guys take a look on this one ? Now all is OK, I will move forward with other PRs.

**Comment by jbonofre** [comment]
The dependency analysis looked to have failed due to Java heap space (it works on my machine).

**Comment by jbonofre** [comment]
@bscholtes1A thanks ! I'm moving on other PRs and issues.

**Pull request merged**
