### PR TITLE
spi: remove policyId from Asset

### LINKED ISSUE #251: Remove PolicyId from Asset
Hello everyone,

the `Asset` currently has a `PolicyId` property. As far as I understand the policies of an `Asset` are described in the corresponding `Contract` or `ContractOffer` class. Therefore I'd remove the `PolicyId` from the `Asset` again.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### PR DESCRIPTION
**Pull request by ndr-brt**
Fix #251

### CODE REVIEW

**Review by bscholtes1A — APPROVED** [review]

**Comment by jimmarino** [comment]
@ndr-brt did you verify the samples as I think some of that code may still be using this?

**Comment by ndr-brt** [comment]
@jimmarino I checked sample 04 and it was not working, but it's not working on `main` branch to, I think it happened with the introduction of the `InlineDataFlowController`. Anyway no issue with the policyId removal.

**Comment by paullatzelsperger** [comment]
> @jimmarino I checked sample 04 and it was not working, but it's not working on `main` branch too, I think it happened with the introduction of the `InlineDataFlowController`. Anyway no issue with the policyId removal.

Hey, just verified. Sample 04 is working, also the sanity checks are green. Don't forget to adapt the file paths, otherwise the file copy won't work.
What problem did you have exactly?

**Comment by ndr-brt** [comment]
@paullatzelsperger I should have add some references on that you're right!
however I opened a discussion about, I got the error because the `DataAddress` miss the `keyName` attribute so the `InlineDataFlowController` returns an error.
I wrote some thoughts and question on this question: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/discussions/519

**Comment by jimmarino** [comment]
@ndr-brt can you resolve and I'll merge?

**Comment by ndr-brt** [comment]
Fixed in this commit: 
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/514/commits/7e93ff57e0790063e9a3179663b5a1ee629ec063

**Comment by jimmarino** [comment]
@ndr-brt are you ready to merge this now?

**Comment by ndr-brt** [comment]
@jimmarino yes

**Pull request merged**
