### PR TITLE
Remove IDS Sample Code, closes #359

### LINKED ISSUE #359: Delete IDS Sample Code
<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### PR DESCRIPTION
**Pull request by DominikPinsel**
<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### CODE REVIEW

**Review by paullatzelsperger — COMMENTED** [review]
This PR does not remove sample code, it rather removes an implementation several downstream projects still rely on, e.g. the Microsoft EDC Showcase and the Catena-X Playground.

Also the Catalog Crawler Subsystem has not yet been moved over to the multipart implementation. 

**I suggest marking all the classes that were deleted here as `@Deprecated` first and delete them later once all downstream dependents have been updated!**

**Comment by jimmarino** [comment]
> This PR does not remove sample code, it rather removes an implementation several downstream projects still rely on, e.g. the Microsoft EDC Showcase and the Catena-X Playground.
> 
> Also the Catalog Crawler Subsystem has not yet been moved over to the multipart implementation.
> 
> **I suggest marking all the classes that were deleted here as `@Deprecated` first and delete them later once all downstream dependents have been updated!**

@paullatzelsperger which implementations are those? Can you point them out so we can separate them from code that can be deleted?

**Comment by paullatzelsperger** [comment]
Like i said, I don't think we should delete anything at this point,  unless we want to break stuff. Except maybe the `DescriptionRequestController`. 

Both the query and the transfer module are still used by samples and downstream repos. 
Either we adapt those first and delete then, or we deprecate all the java classes and delete later.

**Comment by jimmarino** [comment]
Here is a rough proposal for how to do this:

### First, migrate use of ids-api-catalog and remove it
- Samples
- Catalog Crawler
- EDC Showcase 
- Catena-X PRS service and playground

### Second, migrate use of ids-api-transfer
- Samples
- EDC Showcase
- Catena-X PRS service and playground

### Third, remove ids-policy-mock

### Fourth, remove the following IDS-SPI classes:
- DynamicAttributeToken, TokenFormat
- DapsService
- DefaultValues
- IdsPolicyService

### Five, remove PolicyRegistry and policy-registry-memory

@paullatzelsperger did I miss anything? What is the Catena-X playground using of the old modules?

If this accurately captures what needs to be done, I would start #1 by moving the samples (if not already done), followed by the crawler. The EDC showcase can be done separately. At the same time, we need to liaise with the PRS team to get them to migrate over.

**Comment by paullatzelsperger** [comment]
Sounds about right, that should be all. The Catena-X playground is pretty much a carbon-copy or the EDS Showcase installation.

As for chronology, I would sort this by "area" (= crawler, samples, demos...) and move them over one-by-one. That way we only have to touch each area once.

**Comment by DominikPinsel** [comment]
@jimmarino  @paullatzelsperger should I then create issues for the proposed steps and close this PR?

**Comment by paullatzelsperger** [comment]
If you could create the issues, that'd be great. We can leave this PR in place and simply merge it after all those other issues have been completed.

**Comment by DominikPinsel** [comment]
> Here is a rough proposal for how to do this:
> 
> ### First, migrate use of ids-api-catalog and remove it
> * Samples
> * Catalog Crawler
> * EDC Showcase
> * Catena-X PRS service and playground
> 
> ### Second, migrate use of ids-api-transfer
> * Samples
> * EDC Showcase
> * Catena-X PRS service and playground
> 
> ### Third, remove ids-policy-mock
> ### Fourth, remove the following IDS-SPI classes:
> * DynamicAttributeToken, TokenFormat
> * DapsService
> * DefaultValues
> * IdsPolicyService
> 
> ### Fifth, remove PolicyRegistry and policy-registry-memory
> @paullatzelsperger did I miss anything? What is the Catena-X playground using of the old modules?
> 
> If this accurately captures what needs to be done, I would start #1 by moving the samples (if not already done), followed by the crawler. The EDC showcase can be done separately. At the same time, we need to liaise with the PRS team to get them to migrate over.

Reminder for me: Also create a new issue for #299

**Comment by ndr-brt** [comment]
can this be closed?

**Pull request closed without merging**
