### PR TITLE
asset loader: move interface

### LINKED ISSUE #437: SPI - Move `AssetLoader` interface into corresponding SPI
The `AssetLoader` interface, which should be implemented by extensions, is not part of an SPI.
Move it from `extensions/dataloading/dataloding-assets/` to`extensions/dataloading/dataloding-spi/`

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/dataloading/dataloading-asset/src/main/java/org/eclipse/dataspaceconnector/dataloading/AssetLoader.java

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### PR DESCRIPTION
**Pull request by bcronin90**
Closes #437 

Move asset loader into SPI. Update dependencies and README.md.

Brendan Cronin brendan.cronin@daimler.com, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

### CODE REVIEW

**Review by ndr-brt — APPROVED** [review]

**Review by paullatzelsperger — CHANGES_REQUESTED** [review]
The "domain"-specific classes should not go into SPI. SPI just contains the generic extension points and model classes, such as the `DataLoader` and the `DataSink`, whereas specific variants (such as the `AssetLoader` or the `ContractDefinitionLoader`) should remain in separate extensions.

**Comment by ndr-brt** [comment]
@paullatzelsperger maybe should we just rename the `dataloading-asset` in `dataloading-asset-spi`? Because `AssetLoader` is an spi that needs to be implemented by an extension

**Comment by paullatzelsperger** [comment]
> @paullatzelsperger maybe should we just rename the `dataloading-asset` in `dataloading-asset-spi`? Because `AssetLoader` is an spi that needs to be implemented by an extension

that would be a possibility. we'd have to do the same for the `dataloading-contractdef` then

**Comment by paullatzelsperger** [comment]
@ndr-brt I could live with that.

**Comment by bcronin90** [comment]
In accordance with the talk we had today involving @paullatzelsperger @DominikPinsel @MoritzKeppler we will consolidate dataloading into one module for now. Right now there's no need for it to be split.

That means this PR would now close:
#436 
#437

**Review by ndr-brt — APPROVED** [review]

**Comment by bcronin90** [comment]
Can this be merged?

**Review by paullatzelsperger — APPROVED** [review]

**Pull request merged**
