### PR TITLE
DPF: control proxy behavior 

### PR DESCRIPTION
**Pull request by MoritzKeppler**
## What this PR changes/adds
The DPF can act as http proxy. For security reasons it's important to not overwrite values set in the source dataaddress defined at the asset but just take those aspects the data address allows to be taken from the current request.

## Why it does that

security reasons

## Linked Issue(s)

relates to #882

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Comment by bscholtes1A** [comment]
Ok for me as this is something that needs to be delivered soon.

**Comment by bscholtes1A** [comment]
Ok for me as this is to be delivered soon, however this kind of logic should be later on handled through Policies, no ? @jimmarino  @paullatzelsperger WDYT?

**Comment by MoritzKeppler** [comment]
The actual rules what is allowed to be called (e.g. path patterns) should be part of the policies.
But nevertheless it could be of value to configure if a DataAddress is allowed to be used in a proxy behavior or describes a finally defined endpoint. This is typically something that happens during creation of an asset - independent from contract definitions / offers.

**Review by bcronin90 — APPROVED** [review]

**Comment by bscholtes1A** [comment]
> The actual rules what is allowed to be called (e.g. path patterns) should be part of the policies. But nevertheless it could be of value to configure if a DataAddress is allowed to be used in a proxy behavior or describes a finally defined endpoint. This is typically something that happens during creation of

**Comment by MoritzKeppler** [comment]
@bscholtes1A 
We (@paullatzelsperger, @jimmarino, @stefan-ettl, @MoritzKeppler) decided to merge it as it is and check if we need to refactor or improve it later.

**Pull request merged**
