### PR TITLE
Restructure code

### PR DESCRIPTION
**Pull request by beardyinc**
- [x] Change the directory structure to a previously agreed-upon structure
- [x] Change package names to `org.eclipse.edc`
- [x] Adapt CI pipeline
- [ ] Add repository secrets to fix integration tests

### CODE REVIEW

**Comment by MoritzKeppler** [comment]
is "edc" the official shortname of our project? or is it "dataspaceconnector"?
we need to include the shortname as third part in the package names, see https://www.eclipse.org/projects/handbook/#checklist

**Comment by beardyinc** [comment]
> is "edc" the official shortname of our project? or is it "dataspaceconnector"?
> we need to include the shortname as third part in the package names, see https://www.eclipse.org/projects/handbook/#checklist

i think we talked about replacing `com.microsoft.dagx` with `org.eclipse.edc` during last friday's meeting, but I am not 100% certain. We can always change it, but `org.eclipse.dataspaceconnector` feels a bit ... clunky

**Comment by MoritzKeppler** [comment]
> 
> i think we talked about replacing `com.microsoft.dagx` with `org.eclipse.edc` during last friday's meeting, but I am not 100% certain. We can always change it, but `org.eclipse.dataspaceconnector` feels a bit ... clunky

sure it's clunky but as far as I understand we are forced to do so (except we get an approval from our PMC):
https://www.eclipse.org/projects/handbook/#trademarks-code

**Comment by beardyinc** [comment]
no worries, I'll change it out to `org.eclipse.dataspaceconnector`.

**Pull request merged**
