### PR TITLE
Adds a CosmosDB-based impl. for the ContractNegotiationStore

### LINKED ISSUE #309: Implement Cosmos ContractNegotiationStore

### PR DESCRIPTION
**Pull request by paullatzelsperger**
closes #309 

Some improvements to the `CosmosDbApi` were also made, as well as to the `ContractNegotiationStore`.

### CODE REVIEW

**Review by jimmarino — APPROVED** [review]
Thanks @paullatzelsperger

**Comment by jimmarino** [comment]
@paullatzelsperger I merged. Can you give @juliapampus @ronjaquensel a heads up on the introduction of ContractNegitationStore#save instead of save/update? They will need to rebase their branch on top of these changes and it may cause a few conflicts.

**Comment by jimmarino** [comment]
@paullatzelsperger One other q: does this support the Criteria "IN" operator?

**Comment by paullatzelsperger** [comment]
> @paullatzelsperger One other q: does this support the Criteria "IN" operator?

this has nothing to do with the "IN" operator as that solely refers to the `AssetIndex` and will be investigated in a separate issue.

**Pull request merged**
