### PR TITLE
Transfer Process Manager: consistent update of transfer processes

### LINKED ISSUE #324: Inconsistent transfer process updates by TransferProcessManager
The current implementation of the `TransferProcessManager` updates changes to processes in an inconsistent way:
* Sometimes processes are updated although no changes are available. This causes unnecessary write operations and gives issues when updating the state of a process from a separate thread as the TransferProcessManager overwrites the state back constantly.
* Sometimes `TransferProcessListeners` are notified before updating the process, sometimes after.

My suggestion would be to only update processes whenever changes are available and always before notifying `TransferProcessListeners`.

### PR DESCRIPTION
**Pull request by marcgs**
Consistent update of TransferProcesses in `TransferProcessManagerImpl`:

* Only update processes whenever changes are done
* Call `TransferProcessListeners` always after process has been updated

Closes #324

### CODE REVIEW

**Comment by jimmarino** [comment]
Hi @marcgs Can you also sign the ECA? Thx

**Review by paullatzelsperger — APPROVED** [review]
LGTM, but what problem does this solve? Semantically there it's almost identical.

**Review by paullatzelsperger — CHANGES_REQUESTED** [review]
one of the unit tests failed. PRs should only be marked "ready for review" once all the tests are green.

**Comment by marcgs** [comment]
> LGTM, but what problem does this solve? Semantically there it's almost identical.

The TransferProcessManager was constantly updating TransferProcess in a loop, even when this was not necessary. The problem we faced is that is that we did not manage to move the state of a TransferProcess to ERROR after a timeout from a separate watchdog thread, as this was being overwritten almost always. With this change the chance of this happening is way smaller as the TPM will only do so if the process advances to the next state, in which case is it ok as the process was completed roughly at the same time the timeout expired.

Generally I think we should prevent unnecessary write operations as well.

**Comment by marcgs** [comment]
> Hi @marcgs Can you also sign the ECA? Thx

@jimmarino will do ASAP 👍🏻

**Comment by paullatzelsperger** [comment]
@marcgs ok, fair point :)

**Comment by marcgs** [comment]
@paullatzelsperger @jimmarino I signed the ECA. You can go ahead and review the PR.

**Review by paullatzelsperger — APPROVED** [review]

**Pull request merged**
