### PR TITLE
data-protocols: removed deprecated IdsPolicyService and related extension

### PR DESCRIPTION
**Pull request by ndr-brt**
I think we missed this in #493

### CODE REVIEW

**Review by bscholtes1A — APPROVED** [review]

**Review by paullatzelsperger — COMMENTED** [review]
It might be used in downstream projects, but we'll just have to remove it there too then.

**Comment by paullatzelsperger** [comment]
@jimmarino i think we should merge this once all conflicts are resolved.

**Comment by ndr-brt** [comment]
conflict resolved

**Comment by ndr-brt** [comment]
There's a test that sometimes fails randomly for a timeout exception in `MultipartDispatcherIntegrationTest`, however I forced push to re-execute the CI, let's see

**Pull request merged**
