### PR TITLE
fix: validate offer policy equality with definition policy on negotiation

### LINKED ISSUE #1791: Connector accepts **any** Contract Offer
# Bug Report

## Describe the Bug
A connector accepts any contract offers. The content of the contract offer is not checked.

=> It is possible to change a contract in any way. It is not possible to create a contract for assets, the connector would not have access to. 

### Expected Behavior

- Connector accepts only contracts it has offered before.

### Observed Behavior

- Connector accepts **any** contracts.

## Steps to Reproduce
1. Connector_A: Create Asset

```json
{
  "asset": {
    "properties": {
      "asset:prop:id": "1"
    }
  },
  "dataAddress": {
    "properties": {
      "type": "HttpData",
      "baseUrl": "<url>"
    }
  }
}
```

3. Connector_A: Create Policy

```json
{
  "uid": "1",
  "policy": {
    "permissions": [
      {
        "edctype": "dataspaceconnector:permission",
        "action": {
          "type": "USE"
        },
        "constraints": [
          {
            "edctype": "AtomicConstraint",
            "leftExpression": {
              "edctype": "dataspaceconnector:literalexpression",
              "value": "Pay_Me"
            },
            "rightExpression": {
              "edctype": "dataspaceconnector:literalexpression",
              "value": "1000 Euros"
            },
            "operator": "EQ"
          }
        ]
      }
    ]
  }
}
```

4. Connector_A: Create Contract Definition

```json
{
  "id": "1",
  "criteria": [
    {
      "operandLeft": "asset:prop:id",
      "operator": "=",
      "operandRight": "1"
    }
  ],
  "accessPolicyId": "<something public>",
  "contractPolicyId": "1"
}
```

4. Connector_B: Initiate contract negotiation via POST at `/contractnegotiations` API, but does not want to pay (leaves the constraints out).

```json
{
  "connectorId": "foo",
  "connectorAddress": "${Connector_A}/api/v1/ids/data",
  "offer": {
    "offerId": "1:foo",
    "assetId": "1",
    "policy": {
      "uid": "2",
      "permissions": [
        {
          "edctype": "dataspaceconnector:permission",
          "action": {
            "type": "USE"
          },
          "target": "1",
          "constraints": []
        }
      ]
    }
  }
}
```

5. Check contract agreement in database of Connector_A

| agr_id | asset_id | policy |
|:---|:---|:---|
|1:6e9e400c-a411-4cef-8135-047ffd532061 | 1 | {"permissions":[{"edctype":"dataspaceconnector:permission","uid":null,"target":"1","action":{"type":"USE","includedIn":null,"constraint":null},"assignee":null,"assigner":null,"constraints":[],"duties":[]}],"prohibitions":[],"obligations":[],"extensibleProperties":{},"inheritsFrom":null,"assigner":null,"assignee":null,"target":null,"@type":{"@policytype":"set"}} |

## Context Information

- Used version: Milestone 5

## Detailed Description

Catalog from Connector_A:

```json
{
  "id": "default",
  "contractOffers": [
    {
      "id": "1:95cab8a1-b3c5-4d59-b8b7-f8fcc6e4697f",
      "policy": {
        "permissions": [
          {
            "edctype": "dataspaceconnector:permission",
            "uid": null,
            "target": "1",
            "action": {
              "type": "USE",
              "includedIn": null,
              "constraint": null
            },
            "assignee": null,
            "assigner": null,
            "constraints": [
              {
                "edctype": "AtomicConstraint",
                "leftExpression": {
                  "edctype": "dataspaceconnector:literalexpression",
                  "value": "Pay_Me"
                },
                "rightExpression": {
                  "edctype": "dataspaceconnector:literalexpression",
                  "value": "1000 Euros"
                },
                "operator": "EQ"
              }
            ],
            "duties": []
          }
        ],
        "prohibitions": [],
        "obligations": [],
        "extensibleProperties": {},
        "inheritsFrom": null,
        "assigner": null,
        "assignee": null,
        "target": null,
        "@type": {
          "@policytype": "set"
        }
      },
      "asset": {
        "properties": {
          "asset:prop:description": "Product EDC Demo Asset",
          "ids:byteSize": null,
          "asset:prop:id": "1",
          "ids:fileName": null
        }
      },
      "assetId": null,
      "provider": "urn:connector:provider",
      "consumer": "urn:connector:consumer",
      "offerStart": null,
      "offerEnd": null,
      "contractStart": null,
      "contractEnd": null
    }
  ]
}
```

## Possible Implementation

-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### PR DESCRIPTION
**Pull request by ndr-brt**
## What this PR changes/adds

Add an equality check between contract offer policy and contract negotiation policy in `ContractValidationService`

## Why it does that

To avoid injection of malicious policies.

## Further notes

- this check is needed since currently the negotiation is automatically, and no counter offers are supported
- the equality check is done using the `ObjectMapper`'s `ObjectNode` as it is way less disruptive than overriding the `equals` method on every policy model class 
- the `target` has been excluded from the check for reasons explained in the issue: #1791 
- in `ContractValidationServiceImpl` the way the target asset is retrieved has been simplified, since the `id` must always be present, it can be used as the only criteria to get the `Asset`
- I'm not a supporter of "unhappy path e2e tests" but I needed this to light the way to the solution, I would keep it as it is a critical case, but it could be deleted in the future.
- **question**: is the `assetId` in the `ContractOffer` still useful? seems like isn't used by anoyone. I left it as it is, but in my opinion it could be removed.

## Linked Issue(s)

Closes #1791 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Review by jimmarino — COMMENTED** [review]
Let's discuss when I'm back. This touches on issues in the IDS protocol that need to be fixed and the concept of a policy infoset that can be used to derive signatures and equality. For now can't we just throw away the policy on the provider and always regenerate it?

**Comment by ndr-brt** [comment]
> Let's discuss when I'm back. This touches on issues in the IDS protocol that need to be fixed and the concept of a policy infoset that can be used to derive signatures and equality. For now can't we just throw away the policy on the provider and always regenerate it?

@jimmarino do you mean to completely ignore the policy in the offer and to use the policy in the definition? Doing like this there will be inconsistency between the negotiation data on the consumer (it'd have the "modified" policy) and ond the provider (it'd have the original one). Wouldn't be better to explicitly decline the negotiation?

**Review by DominikPinsel — APPROVED** [review]

**Comment by jimmarino** [comment]
@ndr-brt  The provider should never accept the consumer contract offer, even if it is "electronically equal". It should only accept one it has generated. If the consumer has modified the offer in any way, it is a "bug" or malicious intent on the consumer's part. When we implement signing and non-reputation, we can deal with this negative case more robustly.

**Comment by ndr-brt** [comment]
> @ndr-brt  The provider should never accept the consumer contract offer, even if it is "electronically equal". It should only accept one it has generated. If the consumer has modified the offer in any way, it is a "bug" or malicious intent on the consumer's part. When we implement signing and non-reputation, we can deal with this negative case more robustly.

@jimmarino if we implement that logic (the provider will accept the policy it created, regardless of what the consumer sent) it will mean that the consumer request will rely only on the definition id, and every change to the policy will be accepted but without any error, and that's confusing by a consumer perspective. Is this acceptable? If so, I would open a PR with this behavior to have either this or the other merged asap because we need some kind of restriction for malicious intents for the forthcoming C-X release

**Review by paullatzelsperger — APPROVED** [review]
This seems to be a problem in need of a timely fix, so I'm fine with _how_ the change is implemented.
We'll probably want to revisit the topic during/after the upcoming improvements to IDS.

**Review by ronjaquensel — APPROVED** [review]

**Pull request merged**
