### PR TITLE
control-api: Add controller to fetch resource catalog

### PR DESCRIPTION
**Pull request by denisneuling**
Adding the control-api to retrieve catalogs containing contract offers from a data provider.

<sub> Denis Neuling <denis.neuling@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

### CODE REVIEW

**Comment by denisneuling** [comment]
@DominikPinsel Do you want to merge that with your work done in PR #276 - or shall we keep it separated?

**Comment by jimmarino** [comment]
Hi @denisneuling There are types added to SPI that are used by the control-api module. Can you please remove them from SPI and either put them in a separate "model" module that the control-api depends on?

**Comment by DominikPinsel** [comment]
FYI
I resolved the merge conflicts with main and added some minor changes/fixes so that the fetching of the resource catalog works with sample5.

**Comment by denisneuling** [comment]
@jimmarino The dispatcher and the control api modules need some common container object to make known and use of the contract information. I think there is just the way - as is - of having that `ResourceCatalog` container object to be contained in the main `spi` module. Otherwise by introducing another intermediary module exclusively used by dispatcher and control api, we'd couple them to tight together - which would lead to the question why we have separated those both into distinct modules initially. - And I suppose that pretty much clear due to them handling different concerns.

**Comment by denisneuling** [comment]
@jimmarino As discussed `DataCatalog` has been renamed to `Catalog` and `CatalogRequest` has been moved into the same package. The large amount of changed files is due to the import reordering and variable renaming.

**Review by jimmarino — APPROVED** [review]
LGTM, thanks Denis

**Pull request merged**
