### PR TITLE
feat: add docsify

### PR DESCRIPTION
**Pull request by juliapampus**
## What this PR changes/adds

Add [docsify](https://github.com/topics/docsify) as a framework to deploy the current `/docs` directory as a static website using [GitHub pages](https://pages.github.com/). As I already had this work done in an old branch from some months ago, I thought directly creating a PR and showing the impact could help with the discussion.

## Why it does that

In #580, it was already discussed whether a framework should be used and which one. The most important aspect is: Keep it simple and avoid additional overhead. We only need a rendering of the documentation, no fancy EDC website (this will not be done with GitHub pages).

With the DSC, we used "Just the Docs" (see the deployment [here](https://international-data-spaces-association.github.io/DataspaceConnector/)). It worked well and the maintenance was quite easy, but the existing `.md` files needed to be extended with additional metainformation. Therefore, existing files needed to be modified. Hence, I was looking for a framework that would work without any changes. Whatever framework we choose, all support advanced customization, nevertheless, [docsify](https://github.com/topics/docsify) generates web content by simply using the `.md` files as they are.

See a sample rendering [here](https://fraunhoferisst.github.io/EclipseDataspaceConnector/) (click on "Getting started").

## Further notes

As GitHub pages are initially always deployed at the same url, it would not be a problem to change this framework later again - if anyone comes up with a better approach. In addition, this PR only shows the current `.md` files' content, so empty sections and the general toc structure would have to be filled and modified anyway.

## Linked Issue(s)

Closes # <-- _insert Issue number if one exists_

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Comment by juliapampus** [comment]
@florianrusch-zf

**Review by paullatzelsperger — APPROVED** [review]
looks cool! do you know of any way to automatically add the author to the respective pages?

**Comment by juliapampus** [comment]
> looks cool! do you know of any way to automatically add the author to the respective pages?

I will take a look whether docsify comes with a solution. Otherwise, maybe we can add an automatism to add those meta information (last edited, author, modified by, etc.)

**Review by mspiekermann — APPROVED** [review]

**Review by ndr-brt — APPROVED** [review]
@juliapampus can we merge this?

**Comment by paullatzelsperger** [comment]
can we merge this? @MoritzKeppler @alexandrudanciu?

**Review by alexandrudanciu — APPROVED** [review]
Looks great, thank you for the contribution!
The only question I had was if the new EDC logo (the one consisting of connected dots) should be used instead of the incubation logo. But of course, this can be discussed and addressed at a later point.

**Comment by juliapampus** [comment]
@MoritzKeppler @alexandrudanciu @ndr-brt 

I will take a look wether everything is up to date later this day. We can merge it afterwards,. In a next step, I will then check how we can structure this in a better way.

**Comment by juliapampus** [comment]
> Looks great, thank you for the contribution! The only question I had was if the new EDC logo (the one consisting of connected dots) should be used instead of the incubation logo. But of course, this can be discussed and addressed at a later point.

I changed the logo (to edc logo) and chose the green in it as the primary color.

**Pull request merged**
