### PR TITLE
rename registerController->registerResource, remove deprecated method

### PR DESCRIPTION
**Pull request by ppuetsch**
this Pull request
* removes a deprecated method (registerController) and replaces usages with the supported method
* removes components that are not used from the 04-file-transfer example

### CODE REVIEW

**Review by ndr-brt — APPROVED** [review]

**Comment by paullatzelsperger** [comment]
hey @ppuetsch thanks for that. once you resolve the conflicts we can merge this

**Comment by ppuetsch** [comment]
@paullatzelsperger done

**Comment by juliapampus** [comment]
@ppuetsch Could you please take a look why the pipeline is failing?

**Comment by ppuetsch** [comment]
@juliapampus I checked the issue - was able to reproduce it locally and fix it. Let's see if CI passes now.

**Comment by ppuetsch** [comment]
@juliapampus @paullatzelsperger CI green now. Is there anything I can to to help you get this one closed?

**Comment by paullatzelsperger** [comment]
@ppuetsch unfortunately I don't have merge rights, but I think we're good to merge.

**Pull request merged**
