### PR TITLE
Renamed client to consumer

### PR DESCRIPTION
**Pull request by DominikPinsel**
renamed client to consumer whenever a consumer connector was meant

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by DominikPinsel** [comment]
@MoritzKeppler Sorry for the delay, the merge conflict is now resolved :)

**Review by MoritzKeppler — APPROVED** [review]

**Comment by beardyinc** [comment]
Here are some of my thoughts. 
The following files/package names still have relevant occurrences of the term "client:
- `IdsPolicyService.java`
- `samples/commandline/client` contains a namespace `org.eclipse.dataspaceconnector.client....`
- `samples/run-from-junit` contains the class `ClientRunner.java`
- `samples/streaming`: see `PushStreamFlowControllerjava:25`

apart from that there will likely be more `client->consumer` renamings incoming from other PRs but lets defer that for later.

**Comment by DominikPinsel** [comment]
@beardyinc I looked at the context didn't rename all occurrences of the client. Therefore these clients should still exist.

**Comment by DominikPinsel** [comment]
@beardyinc done :) Thanks for the input!

**Comment by beardyinc** [comment]
I am not allowed to approve formally, but from my point of view this can be merged.

**Pull request merged**
