### PR TITLE
docs: correct port of the file transfer process for the data consumer (9192)

### PR DESCRIPTION
**Pull request by Julian-Marco**
## What this PR changes/adds

Correct port of the file transfer process for the data consumer (9192)

## Why it does that

The change was necessary because the documentation contained the wrong port (9191)

### CODE REVIEW

**Review by ndr-brt — APPROVED** [review]

**Comment by ndr-brt** [comment]
Hey @Julian-Marco thanks for the fix, you need to change the PR name according to the convention and add at least one label, if you don't have enough permissions to do that we can do that

**Comment by Julian-Marco** [comment]
Hey @ndr-brt! I changed the title (hopefully in a correct kind of way), but I don't have the permission to give the PR a label, so feel free to do it for me.

**Comment by ndr-brt** [comment]
@Julian-Marco please take a look at the [pr etiquette](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/pr_etiquette.md) to get the pr title rules.
Label added

**Comment by paullatzelsperger** [comment]
I realize that this is a really minor fix, but in the future please stick to the established process as per PR etiquette: a bug issue should be created first, and the implementation PR should follow.

**Review by paullatzelsperger — APPROVED** [review]

**Pull request merged**
