### PR TITLE
refactor: move vault accessors to the ServiceExtensionContext class

### LINKED ISSUE #1237: Give to non-injectable services a dedicated method on the `ServiceExtensionContext`
# Feature Request

Currently, services like `Vault`, `PrivateKeyResolver` and `CertificateResolver` that are registered by default are obtained throught the `ServiceExtensionContext.getService`, this is unclear because that method is used to get services that are injected through `@Inject` or required by `@Requires` but these services are not provided by anyone.

## Which Areas Would Be Affected?
core

## Why Is the Feature Desired?
Having dedicated methods on the context will avoid ambiguity.

## Solution Proposal
-

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

### PR DESCRIPTION
**Pull request by ndr-brt**
## What this PR changes/adds

Move `Vault`, `PrivateKeyResolver` and `CertificateResolver` to `ServiceExtensionContext`

## Why it does that

Currently the `Vault`/`PrivateKeyResolver`/`CertificateResolver` are not "injectable" (with the `@Inject` annotation) by anyone because they aren't "provided" (with the `@Provides` annotations), because they are mandatory and loaded at the "runtime" stage.
This is pretty confusing, so I moved their instance to the context class as the other mandatory services (like monitor, type manager, telemetry and so on...)

## Further notes

- Inlined some code from the `ExtensionLoader.loadVault` to the `BaseRuntime` as there was too much indirection (and static methods are not good for keeping such behavior)
- switching the vault-related `registerServiceMock` calls to the `registerSystemExtension` as a vault extension should be registered otherwise the `Null` one will be loaded

## Linked Issue(s)

Closes #1237 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Comment by jimmarino** [comment]
@ndr-brt @paullatzelsperger  Can't we just makes these injectable? It seems like we are starting to add too much to the ServiceExtensionContext.

**Comment by ndr-brt** [comment]
@jimmarino what should differentiate a service that needs to be in the context and one that needs to be injected? Should also `Monitor`, `TypeManager` and `Telemetry` being "injectable"?

**Comment by paullatzelsperger** [comment]
> @jimmarino what should differentiate a service that needs to be in the context and one that needs to be injected? Should also `Monitor`, `TypeManager` and `Telemetry` being "injectable"?

@ndr-brt I like the idea of having the `Vault` etc. as "normal" services, thus being registered into the context, just like normal services. We could still have dedicated methods `getVault()` or `getTypemanager()` on the service context, if we need them. WDYT?

**Comment by jimmarino** [comment]
> @jimmarino what should differentiate a service that needs to be in the context and one that needs to be injected? Should also `Monitor`, `TypeManager` and `Telemetry` being "injectable"?

+1 on making those injectable

**Comment by ndr-brt** [comment]
Fine for me, same for `Monitor`, `TypeManager` and `Telemetry` I imagine. Will close this and open an issue about.

**Pull request closed without merging**
