### PR TITLE
First approach for an Usage Control meta structure

### PR DESCRIPTION
**Pull request by sebbader-sap**
## What this PR changes/adds

Extend the docs section about the Usage Control architecture with a first structure.

## Why it does that

Current discussions about Usage Control do not have a common ground or use the same terminology, leading to inefficiencies and misunderstandings. A comprehensive picture will help to align our internal understanding of the topic as well as serve as a vehicle for documentation and outside communication in general.

## Further notes

only the docs/architecture/usage-control/ folder

Note: This PR is a `draft` to enable others to contribute to the topic, too.

## Linked Issue(s)

Contributes to #1406 and #1229

## Checklist

- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Comment by jimmarino** [comment]
Hi,

Thanks for sharing your views on policy and usage control. I think a better format for this would be a discussion rather than a PR since the contents of this PR are more speculative in nature and don’t take into account existing EDC policy design and relevant code. Documentation that gets checked into this repository needs to be grounded either in the existing code or an accepted design approach (typically a decision record). 

Some specific comments along those lines:

1. Please consider the existing `PolicyEngine` design, particularly extensibility, policy functions, scopes, and bindings. There is documentation on each of these areas (which could be improved) and architecture decision records. This architecture was designed in the context of ODRL, XACML, and other relevant technologies.

2. Similarly, the EDC was architected to accommodate both top-down and bottom-up access control scenarios, as well as the ability to perform “late-binding” access control on assets. The relevant concepts here are `ContractDefinition` and asset selectors.

3. I’m not sure why the RDF document is needed. It’s orthogonal to the runtime as we’re not using RDF structures to represent data in the system. Since ODRL can be represented as an RDF structure, and the EDC policy model is close to ODRL, users can create extensions that provide RDF-related capabilities such as querying or data introspection. Those capabilities shouldn’t be included in the core runtime. 

I’d suggest moving this over to a discussion. If the outcome of that discussion is documentation, a high-level usage control overview could be placed in the [collateral repository](https://github.com/eclipse-dataspaceconnector/Collateral), while this repository is reserved for technical subjects related directly to the code.

Should we move this over to a discussion?

**Comment by sebbader** [comment]
Hi @jimmarino,
this PR is intended as a first step for a comprehensive picture on Usage Control and how the EDC positions itself in there. As such, locating it in this repository is on purpose. 

Regarding your points:
1. The `PolicyEngine` concept is of course one of most critical ones for the enforcement - but nevertheless only providing value if embedded into a consistent conceptual context. ODRL or XACML are technologies to provide the descriptive layer of that but not more.
2. No objections
3. That's actually an error and a left-over from a previous commit. Will remove it.

So why now having the PR? This one will not be a personal work of mine, and I need place where we can collaborate on the files together. Especially as I expect a few implications for the longer term, I do not want to "hide" the discussion in some forked repo and then surprise everyone with one big shot. We can redirect it into a feature branch or similar, no problem.

**Comment by jimmarino** [comment]
> Hi @jimmarino, this PR is intended as a first step for a comprehensive picture on Usage Control and how the EDC positions itself in there. As such, locating it in this repository is on purpose.

If that’s the case, it should definitely go in the [Collateral Repository](https://github.com/eclipse-dataspaceconnector/Collateral). Documentation located under /architecture is intended to be grounded in EDC code and design. This document is not concerned with the technical details of the EDC.

The Collateral Repository is not a “forked” or “hidden” repository. It is intended for exactly what you want – a mechanism for collaborating on and disseminating general information about the EDC. 

> 
> Regarding your points:
> 
> 1. The `PolicyEngine` concept is of course one of most critical ones for the enforcement - but nevertheless only providing value if embedded into a consistent conceptual context. ODRL or XACML are technologies to provide the descriptive layer of that but not more.

The existing policy architecture (which encompasses both access and usage control) was designed with a conceptual context in mind and a lot of work has gone into it. It would be really useful if those were documented and taken as the starting point for positioning the EDC as they are the “facts on the ground.”

> 2. No objections
> 3. That's actually an error and a left-over from a previous commit. Will remove it.
> 
> So why now having the PR? This one will not be a personal work of mine, and I need place where we can collaborate on the files together. Especially as I expect a few implications for the longer term, I do not want to "hide" the discussion in some forked repo and then surprise everyone with one big shot. We can redirect it into a feature branch or similar, no problem.

Feature branches are for code. Again, the Collateral Repository was intended for this purpose, and the documentation you propose will receive more visibility there instead of being buried in technical minutiae contained in a code repository. It will also avoid requiring the technical committers to review these PRs, which will be a bottleneck on merging and collaborating.

**Comment by sebbader-sap** [comment]
We have discussed the target place for the PR's content and will put it - with a few updates - in a respective folder in the Collateral repo, also as a reference for similar concept-oriented topics.

**Pull request closed without merging**
