### PR TITLE
project: Set Java 17 as build version

### LINKED ISSUE #649: Java 17
At the EDC conf someone asked why we aren't using java 17.
Since it's the newest LTS released and since we've not released something stable yet could be a good moment to upgrade.

From a language perspective, there are some nice new features as `record` classes and improved pattern matching for `switch` case expressions

### PR DESCRIPTION
**Pull request by ndr-brt**
## What this PR changes/adds

Introduce Java 17 as build system

## Why it does that

Java 17 is the latest LTS available, and it's good to keep the version updated. 
Java 11 still remains as build target version.

## Further notes

- Removed some code that was using code that was dropped by Java 16 ([more info](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/649#issuecomment-1033553832)).
- Upgraded Gradle Wrapper at 7.4.1

## Linked Issue(s)

Closes #649 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Comment by jimmarino** [comment]
@paullatzelsperger is the elliptic curve stuff still used?

**Comment by paullatzelsperger** [comment]
> @paullatzelsperger is the elliptic curve stuff still used?

as far as I recall that was located in the ION code somewhere, specifically the `secp256k1` curve caused the problem. now that's gone, I think we are good to go.

**Review by paullatzelsperger — COMMENTED** [review]
I found more occurrences of "11" in: 
- `README.md#L28`
- `testing.md#L153+L156`
- `onboarding.md#L12+L13`

**Comment by ndr-brt** [comment]
> I found more occurrences of "11" in:
> 
> * `README.md#L28`
> * `testing.md#L153+L156`
> * `onboarding.md#L12+L13`

The occurrencies on `README.md` and `onboarding.md` report `11+`, and I think this is ok, since 11 becomes a lower bound, so EDC can still be built with Java 11.

Fixed the other occurrencies

**Comment by jimmarino** [comment]
@ndr-brt @paullatzelsperger let me know when you want this merged.

**Review by paullatzelsperger — APPROVED** [review]

**Comment by paullatzelsperger** [comment]
> @ndr-brt @paullatzelsperger let me know when you want this merged.

good for me. approvde.

**Pull request merged**
