### PR TITLE
Added CosmosDB-based AssetIndex  integrationtest to i-test workflow

### PR DESCRIPTION
**Pull request by paullatzelsperger**
I-Tests need to be enabled explicitly by adding a job to the workflow file.

### CODE REVIEW

**Comment by paullatzelsperger** [comment]
@bscholtes1A I noticed that we hadn't enabled this test. can you review this PR?

**Comment by bscholtes1A** [comment]
> @bscholtes1A I noticed that we hadn't enabled this test. can you review this PR?

Hi @paullatzelsperger 
thanks for spotting! I think we also need to add the cosmos federated cache node directory, could you please add it?

Sorry that I missed that in the first place.

**Comment by paullatzelsperger** [comment]
@bscholtes1A done.

**Comment by bscholtes1A** [comment]
> @bscholtes1A done.

I dont have the button to approve, but for me that s ready for merge!

**Review by bscholtes1A — APPROVED** [review]

**Review by jimmarino — APPROVED** [review]

**Pull request merged**
