### PR TITLE
Change names

### PR DESCRIPTION
**Pull request by jimmarino**
Cleanup leftover DA-GX names

### CODE REVIEW

**Review by MoritzKeppler — CHANGES_REQUESTED** [review]
found two more "Gaia-X Data Appliance" occurences in terraform scripts

**Comment by beardyinc** [comment]
be careful with replacing stuff in terraform scripts, they sometimes point to existing resources (such as the state backend). Simply replacing them will break stuff.

**Comment by jimmarino** [comment]
It looks like there are two instances, both related to the organization. One is commented out. @beardyinc can you take a look at those to instances to see if they are safe to change?

**Comment by beardyinc** [comment]
Ok, i took a look, seems those two occurrences of `"Gaia-X Data Appliance"` can be changed safely since they're there just for informational purposes.

**Review by MoritzKeppler — APPROVED** [review]

**Pull request merged**
