### PR TITLE
docs: Document `data-plane-api` and small refactoring

### PR DESCRIPTION
**Pull request by bscholtes1A**
## What this PR changes/adds

Document `data-plane-api` extension:

- Add README file providing background and some technical documentation about the Data Plane API.
- Add OpenAPI documentation.

We take opportunity of this PR for a minor refactoring and some unit-tests improvement.

## Why it does that

Provide missing documentation.

## Linked Issue(s)

Contributes to #1382 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Review by jimmarino — APPROVED** [review]

**Comment by florianrusch-zf** [comment]
@bscholtes1A I am currently wondering whether the async push case should also be described in the use cases. Doesn't the API also play a role in this?

**Comment by bscholtes1A** [comment]
> @bscholtes1A I am currently wondering whether the async push case should also be described in the use cases. Doesn't the API also play a role in this?

All "provider push" transfers are asynchronous, including the one that I described in the markdown file. This is why the Control API exposes a "getTransferState" endpoint which enables to track the state of an on-going asynchronous data transfer.

**Review by ndr-brt — APPROVED** [review]

**Comment by paullatzelsperger** [comment]
removing myself, as there are already sufficient reviewers

**Comment by florianrusch-zf** [comment]
> All "provider push" transfers are asynchronous, including the one that I described in the markdown file. This is why the Control API exposes a "getTransferState" endpoint which enables to track the state of an on-going asynchronous data transfer.

ok, but I was speaking about the async-async push 😅 Means on provider side happens a provisioning. Don't know if this flow fits into this documentation or if there is somewhere a better place for it.

**Pull request merged**
