### PR TITLE
DPF: add TransferRequestDto id

### LINKED ISSUE #1182: Data management API: Transfer process: can't create more than one transfer
# Bug Report

## Describe the Bug

If different data transfers are created (`POST /api/v1/data/transferprocess`) for the same asset, the same ID is returned back. The reason is that the `DataTransfer.id` field is not populated (as it is not present in `DataTransferDto`), and the idempotency mechanism in `TransferProcessManagerImpl#initiateRequest` is based on it.

## Possible Implementation
- Add id to DataTransferDto and convert it

### PR DESCRIPTION
**Pull request by algattik**
## What this PR changes/adds

Add id to TransferRequestDto and support it in converter to TransferRequest

## Why it does that

If different data transfers are created (POST /api/v1/data/transferprocess) for the same asset, the same ID is returned back. The reason is that the DataTransfer.id field is not populated (as it is not present in DataTransferDto), and the idempotency mechanism in TransferProcessManagerImpl#initiateRequest is based on it.

## Further notes

Also deleted a (unused) duplicate `TransferRequestDto` class

## Linked Issue(s)

Closes #1182 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Review by ndr-brt — APPROVED** [review]

**Comment by algattik** [comment]
We could also allow the client optionally not to generate an ID, and have the server generate one in that case. Personally I'd rather not add code paths that are not necessary, as this creates more testing and validation work - the client can just generate a random UUID. Agree @ndr-brt @bscholtes1A @paullatzelsperger ?

**Comment by florianrusch-zf** [comment]
@ndr-brt this PR reflects what we were talking about this morning, doesn't it?

**Comment by ndr-brt** [comment]
@algattik I agree on generating a random UUID in the case the `DataRequestDto.is` is null

**Comment by bscholtes1A** [comment]
> @algattik I agree on generating a random UUID in the case the `DataRequestDto.id` is null

As discussed, I am also in favor of generating a random id if none is provided in the request, i.e. make id optional.

**Comment by algattik** [comment]
@ndr-brt @bscholtes1A thanks for the feedback, I've implemented "generating a random id if none is provided in the request" per this discussion.

**Review by bscholtes1A — APPROVED** [review]

**Pull request merged**
