### PR TITLE
feat: implement contract negotiation part 2

### PR DESCRIPTION
**Pull request by juliapampus**
- [x] Implement `ConsumerContractNegotiationManagerImpl`
- [x] Implement `ProviderContractNegotiationManagerImpl`
- [x] Implement `InMemoryContractNegotiationStore` and `InMemoryContractNegotiationStoreExtension`
- [x] Extend `ContractServiceExtension`
- [x] Implement state transitions in `ContractNegotiation`
- [x] Add tests

### CODE REVIEW

**Comment by juliapampus** [comment]
@jimmarino Do we store the original contract offers in the negotiation object or always the sanitized ones? If we only store the sanitized ones, the hash validation would never be valid, would it?

**Comment by jimmarino** [comment]
Hi @juliapampus and @ronjaquensel I know this is still a draft but I noticed that the WaitStrategy and RemoteMessageDispatcherRegistry are shared by the transfer and contract extensions. Is this something we can solve by introducing a core "foundation" module that the two depend on? If so, can we do this in a separate pull request that we rebase this on? I have some time tomorrow to help with this if needed.

If that will cause too much churn, should we wait until after this PR is merged, in which case we add the duplicate code with @Deprecated and replace it with a subsequent PR?

**Comment by juliapampus** [comment]
Hi @jimmarino, yes, we know. I also added a comment and marked this as a TODO so we will not forget it. Just copied the classes as it was the easiest solution for now. If you have time for that, please feel free to refactor in another PR. As this may not be that important for milestone 1, I think we can also do it afterwards. We also thought about cleaning up the the whole negotiation code as there is a lot of duplicated code. However, @ronjaquensel wants to test these things today, so we can merge it and add the other two PRs. Feel free to help to add validation or the hash checking, or change things you think are implemented wrong or not as it was intended by you. @denisneuling can of course help if he has nothing else on his backlog. We need to merge this for PR #315 and #318.

**Comment by jimmarino** [comment]
> Hi @jimmarino, yes, we know. I also added a comment and marked this as a TODO so we will not forget it. Just copied the classes as it was the easiest solution for now. If you have time for that, please feel free to refactor in another PR. As this may not be that important for milestone 1, I think we can also do it afterwards. We also thought about cleaning up the the whole negotiation code as there is a lot of duplicated code. However, @ronjaquensel wants to test these things today, so we can merge it and add the other two PRs. Feel free to help to add validation or the hash checking, or change things you think are implemented wrong or not as it was intended by you. @denisneuling can of course help if he has nothing else on his backlog. We need to merge this for PR #315 and #318.

OK, that makes sense. Let's leave the duplicate code but mark it with @FIXME or something similar and we can refactor in a separate PR, probably after the milestone.

**Review by jimmarino — APPROVED** [review]
Looks good, can you just look at the failing sanity check?

**Pull request merged**
