### PR TITLE
Bugfix/221 fix flaky itests

### PR DESCRIPTION
**Pull request by paullatzelsperger**
This should fix the brittle integration tests for Azure and S3. I added defensive measures like timeouts and wait times to the tests as well as additional catch blocks to the code.

I also renamed the Integration tests to `*IntegrationTest`.

We'll know for sure only _after_ the merge though.

### CODE REVIEW

**Comment by ndr-brt** [comment]
I think this should be merged. 
It's still failing sometimes because the `pull_request_target` workflow configuration, the integration tests are launched from the checkout of the target of the pull request (main) and not from the code of the PR.
This is safer because no unsafe workflow code can be executed from a PR, but it makes the execution of the IT useless on the PR because the code tested will be always the one on the main branch.

Take a look at the commit hash logged in the checkout phase for confirmation:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/4311160262?check_suite_focus=true

**Comment by paullatzelsperger** [comment]
I agree, it makes modifying the itests themselves a bit of a trial-and-error endeavour. 
Let's merge and adapt if necessary

**Comment by jimmarino** [comment]
@paullatzelsperger The AWS test continually fails. Cal you take a look?

**Comment by paullatzelsperger** [comment]
as @ndr-brt pointed out, due to the fact how i-tests are set up (`pull_request_target`) the fixed tests will only run after the merge.

**Review by jimmarino — APPROVED** [review]

**Comment by jimmarino** [comment]
merging as the the merge will fix the broken tests

**Pull request merged**
